version: '3'

services:
  # MySQL
  db:
    image: mysql:oracle
    container_name: fastapi_mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.conf:/etc/mysql/conf.d/my.cnf
      - ./mysql/store:/var/lib/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=fastapi
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=fastapi
      - TZ=Asia/Tokyo
    restart: always

  api2:
    build: ./src
    container_name: api2
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - 'db'
    environment:
      - TZ=Asia/Tokyo

  python3:
    restart: 'always'
    build:
      context: .
      dockerfile: ./docker/camera.Dockerfile
    container_name: 'python3'
    working_dir: '/root/src'
    tty: true
    volumes:
      - .:/root/src

  api:
    links:
      - db
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: api
    ports:
      - 8000:8000
    tty: true
    volumes:
    - ./api:/api
    stdin_open: true
    networks:
      - local-net

  front:
    build:
      context: .
      dockerfile: ./docker/front.Dockerfile
    container_name: front
    ports:
      - 3000:3000
    command: sh -c "cd react-project && yarn start"
    volumes:
    - ./front:/front/react-project
    tty: true
    stdin_open: true

networks:
  local-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  code_share:
