version: '3'

services:
  # MySQL
  db:
    container_name: "db"
    # path配下のDockerfile読み込み
    build: 
      context: .
      dockerfile: ./docker/db.Dockerfile
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net

  python3:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/camera.Dockerfile
    container_name: 'python3'
    working_dir: '/root/src'
    tty: true
    volumes:
      - .:/root/src

  api:
    links:
      - db
    build: 
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: biblio-api
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    command: uvicorn custom_search:app --reload --host 0.0.0.0 --port 8000
    tty: true
    stdin_open: true
    networks:
      - local-net

  front:
    build: 
      context: .
      dockerfile: ./docker/front.Dockerfile
    container_name: biblio-front
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    command: npm run start
    tty: true 
    stdin_open: true

networks:
  local-net:
    driver: bridge